# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-10 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professorday',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='professorday',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
