# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-10 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams_scheduler', '0002_auto_20160810_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='name_short',
            field=models.CharField(default='\u0410\u0440\u0441\u043b\u0430\u043d\u043e\u0432 \u041c. \u041c.', max_length=16),
            preserve_default=False,
        ),
    ]
